[package]
name = "yuyan-swift-vpn"
version = "1.0.17"
edition = "2021"

[lib]
name = "yuyan_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri = { version = "2", features = ["default", "image-png", "tray-icon"] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
tauri-plugin-single-instance = "2"
tauri-plugin-autostart = "2"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "stream"] }
tokio = { version = "=1.43.0", features = ["fs", "io-util", "time", "process", "sync", "rt", "macros", "net"] }
sha2 = "0.10"

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2.7"
cocoa = "0.25.0"

[target.'cfg(target_os = "windows")'.dependencies]
getrandom = "0.3"
windows-sys = { version = "0.59", features = [
  "Win32_Foundation",
  "Win32_Security",
  "Win32_Security_Authorization",
  "Win32_System_Console",
  "Win32_System_JobObjects",
  "Win32_System_Threading",
  "Win32_UI_Shell",
  "Win32_UI_WindowsAndMessaging",
] }

[profile.release]
opt-level = "z"       # 针对二进制文件体积进行极致优化（体积小可以大幅提升启动速度和减少磁盘占用）
lto = true            # 开启全局链接时优化 (Link Time Optimization)
codegen-units = 1     # 限制编译单元为 1，生成更高效的机器码，且体积更小
panic = "abort"       # 发生 panic 时直接中止进程而不展开调用栈，显著减小体积
strip = true          # 自动剥离符号表与调试信息，大幅压缩最终发布的包体积
